apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintwin-backend
  namespace: fintwin-staging
  labels:
    app: fintwin-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintwin-backend
  template:
    metadata:
      labels:
        app: fintwin-backend
    spec:
      containers:
      - name: backend
        image: fintwin-backend:staging
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fintwin-secrets
              key: JWT_SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: fintwin-secrets
              key: ENCRYPTION_KEY
        - name: ML_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: ML_SERVICE_URL
        - name: ICAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: fintwin-secrets
              key: ICAI_API_KEY
        - name: GST_API_KEY
          valueFrom:
            secretKeyRef:
              name: fintwin-secrets
              key: GST_API_KEY
        - name: AA_API_KEY
          valueFrom:
            secretKeyRef:
              name: fintwin-secrets
              key: AA_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fintwin-staging
  labels:
    app: fintwin-backend
spec:
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: fintwin-backend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fintwin-backend-hpa
  namespace: fintwin-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fintwin-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
