apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintwin-frontend
  namespace: fintwin-staging
  labels:
    app: fintwin-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fintwin-frontend
  template:
    metadata:
      labels:
        app: fintwin-frontend
    spec:
      containers:
      - name: frontend
        image: fintwin-frontend:staging
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: NODE_ENV
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: fintwin-config
              key: API_URL
        - name: NEXT_PUBLIC_APP_ENV
          value: "staging"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fintwin-staging
  labels:
    app: fintwin-frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: fintwin-frontend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fintwin-frontend-hpa
  namespace: fintwin-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fintwin-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
